name: songtube
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.0.0+80

environment:
  sdk: ">=2.2.2 <3.0.0"
  shared_preferences: '>=0.5.7+3 <2.0.0'
  share: '>=0.6.4+3 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Media Playback Packages
  flutter_audio_query: ^0.3.5+6
  video_player:
    git:
      url: https://github.com/SongTube/plugins
      path: packages/video_player/video_player
      ref: master
  just_audio: ^0.5.4
  audio_service: ^0.15.1
  sliding_up_panel:
    git:
      url: git://github.com/SongTube/sliding_up_panel.git
      ref: master

  # NewPipe Extractor
  newpipeextractor_dart:
    git:
      url: https://github.com/SongTube/newpipeextractor_dart
      ref: master

  # Device Providers
  shared_preferences: ^0.5.10
  provider: ^4.1.2
  device_info: ^0.4.2+4
  path_provider: any
  package_info: ^0.4.1
  ext_storage: ^1.0.3
  permission_handler: 5.1.0+2
  file_picker: ^2.1.6
  path: ^1.7.0

  # Text
  intl: ^0.17.0-nullsafety.2
  string_validator: ^0.1.4

  # HTTP
  dio: any
  http: any
  flutter_inappwebview: ^4.0.0+4

  # Icons
  material_design_icons_flutter: ^4.0.5345
  eva_icons_flutter: ^2.0.0

  # Animations
  shimmer: ^1.1.1
  avatar_glow: ^1.2.0
  flutter_glow: ^0.1.2
  autolist:
    git:
      url: git://github.com/SongTube/autolist.git
      ref: master
  image_fade: ^0.2.1
  animations: ^1.1.2

  # Tools
  share: ^0.6.4+3
  flutter_ffmpeg:
    git:
      url: https://github.com/SongTube/flutter-ffmpeg
      ref: master
  url_launcher: ^5.4.7
  transparent_image: ^1.0.0
  grouped_list: ^3.5.0
  volume: ^1.0.1
  flutter_screen: ^0.0.2
  
  # Database
  sqflite: ^1.3.0

  # Misc
  flutter_xlider: ^3.4.0
  flutter_material_color_picker: ^1.0.5
  circular_check_box: ^1.0.1
  flutter_keyboard_visibility: ^3.2.1
  flutter_staggered_grid_view: ^0.3.2
  palette_generator: ^0.2.3
  flutter_markdown: ^0.5.0
  md2_tab_indicator: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/LICENSE
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: YTSans
      fonts:
        - asset: assets/fonts/youtube-sans-medium.ttf
          weight: 500
        - asset: assets/fonts/youtube-sans-light.ttf
          weight: 300
        - asset: assets/fonts/youtube-sans-bold.ttf
          weight: 700
    - family: Product Sans
      fonts:
        - asset: assets/fonts/productSans/bold.ttf
          weight: 700
        - asset: assets/fonts/productSans/regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
