name: songtube
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+0

environment:
  sdk: ">=2.2.2 <3.0.0"
  shared_preferences: '>=0.5.7+3 <2.0.0'
  share: '>=0.6.4+3 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: any
  path_provider: any
  package_info: ^0.4.1
  intl: ^0.16.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.7+3
  provider: ^4.1.2
  device_info: ^0.4.2+4
  http: any
  youtube_explode_dart: ^1.4.2
  ext_storage: ^1.0.3
  permission_handler: ^5.0.0+hotfix.3
  youtube_player_flutter: ^6.1.0+7
  flutter_ffmpeg: ^0.2.10
  path: ^1.7.0
  url_launcher: ^5.4.7
  transparent_image: ^1.0.0
  material_design_icons_flutter: ^4.0.5345
  just_audio: ^0.2.1
  sqflite: ^1.3.0
  flutter_xlider: ^3.4.0
  flutter_inappwebview: ^3.3.0+3
  eva_icons_flutter: ^2.0.0
  audio_service: ^0.11.0
  shimmer: ^1.1.1
  flutter_material_color_picker: ^1.0.5
  circular_check_box:
    git:
      url: git://github.com/not-holar/circular_check_box.git
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_launcher.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
